service: aws-bam-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:987795168930:table/TaskTable"

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  createBook:
    handler: src/addBook.addBook
    events:
      - httpApi:
          path: /libros
          method: post
  getBook:
    handler: src/getBook.getBook
    events:
      - httpApi:
          path: /libros/{id}
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH           
